name: First Workflow
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: Multiline Command
        run: |
          echo "Node version: " 
          node -v

  parallel-job-macos:
    runs-on: macos-latest
    steps:
      - name: View SW Version
        run: sw_vers
      - name: Multiline Command
        run: |
          echo "NPM version: "
          npm -v
